## Задание 1.

In [1]:
import pandas as pd

* Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices
* Считать данные с помощью pandas
* Вывести на экран первые 5 строк
* Посмотреть на описание признаков и на их содержание

1. Company - компания, которая производит ноутбуки
2. Product - имя ноутбука
3. TypeName - тип ноутбука
4. Inches - диагональ
5. ScreenResolution - разрешение ноутбука 
6. Cpu - процессор
7. Ram - ОЗУ
8. Memory - память
9. Gpu - видеокарта
10. OpSys - операционная система
11. Weight - вес ноутбука
12. Price - стоимость ноутбука

In [2]:
df = pd.read_csv('./laptops_10.csv')

In [3]:
df.head()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,FlashStorage
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company        1303 non-null   object
 1   Product        1303 non-null   object
 2   TypeName       1303 non-null   object
 3   Inches         1303 non-null   float64
 4   Cpu            1303 non-null   object
 5   Ram            1303 non-null   object
 6   Gpu            1303 non-null   object
 7   OpSys          1303 non-null   object
 8   Weight         1303 non-null   float64
 9   Price_euros    1303 non-null   float64
 10  Cpu_Company    1303 non-null   object
 11  Memory_Amount  1303 non-null   int64
 12  Memory_Type    1303 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 132.5+ KB

In [5]:
df.isnull()

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,False,False,False,False,False,False,False,False,False,False,False,False,False
1299,False,False,False,False,False,False,False,False,False,False,False,False,False
1300,False,False,False,False,False,False,False,False,False,False,False,False,False
1301,False,False,False,False,False,False,False,False,False,False,False,False,False
1302,False,False,False,False,False,False,False,False,False,False,False,False,False

In [6]:
df.isnull().sum()

Company          0
Product          0
TypeName         0
Inches           0
Cpu              0
Ram              0
Gpu              0
OpSys            0
Weight           0
Price_euros      0
Cpu_Company      0
Memory_Amount    0
Memory_Type      0
dtype: int64

In [7]:
df.describe()

            Inches       Weight  Price_euros  Memory_Amount
count  1303.000000  1303.000000  1303.000000    1303.000000
mean     15.017191     2.038734  1123.686992     447.809670
std       1.426304     0.665475   699.009043     366.037159
min      10.100000     0.690000   174.000000       8.000000
25%      14.000000     1.500000   599.000000     256.000000
50%      15.600000     2.040000   977.000000     256.000000
75%      15.600000     2.300000  1487.880000     512.000000
max      18.400000     4.700000  6099.000000    2048.000000

In [8]:
df.describe(include = ['object'])

,Company,Product,TypeName,Cpu,Ram,Gpu,OpSys,Cpu_Company,Memory_Type
count,1303,1303,1303,1303,1303,1303,1303,1303,1303
unique,19,618,6,118,9,110,9,3,4
top,Dell,XPS 13,Notebook,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,Windows 10,Intel,SSD
freq,297,30,727,190,619,281,1072,1240,641

## Задание 2.

* Проведите первичный анализ данных.
* Изучите типы данных.
* Найдите количество пропущенных ячеек в данных.
* Посчитайте основные статистики по всем признакам и поизучайте их.

## Задание 3.

Ответьте на несколько вопросов

* 3.1 Ноутбуков от какой компании больше всего в наборе данных?
* 3.2 Какая минимальная и максимальная стоимость у ноутбуков в данных?
* 3.3 Какой самый дорогой ноутбук в данных?

Выведите все характеристики только по этому ноутбуку

Если таких ноутбуков несколько, то выводите их всех

In [9]:
df['Company'].value_counts()

Dell         297
Lenovo       297
HP           274
Asus         158
Acer         103
MSI           54
Toshiba       48
Apple         21
Samsung        9
Razer          7
Mediacom       7
Microsoft      6
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Fujitsu        3
LG             3
Huawei         2
Name: Company, dtype: int64

In [10]:
df['Price_euros'].max()

6099.0

In [11]:
df['Price_euros'].min()

174.0

In [12]:
max_price = df['Price_euros'].max()

In [13]:
df[df['Price_euros'] == max_price]

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
196,Razer,Blade Pro,Gaming,17.3,Intel Core i7 7820HK 2.9GHz,32GB,Nvidia GeForce GTX 1080,Windows 10,3.49,6099.0,Intel,1024,SSD

pd.set_option() - все вывести

In [14]:
df[df['Price_euros'] == df['Price_euros'].min()]

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
1215,Acer,C740-C9QX (3205U/2GB/32GB/Chrome,Netbook,11.6,Intel Celeron Dual Core 3205U 1.5GHz,2GB,Intel HD Graphics,Chrome OS,1.3,174.0,Intel,32,SSD

или

In [15]:
df[df['Price_euros'] == 9270.72]

Empty DataFrame
Columns: [Company, Product, TypeName, Inches, Cpu, Ram, Gpu, OpSys, Weight, Price_euros, Cpu_Company, Memory_Amount, Memory_Type]
Index: []

In [16]:
df[df['Price_euros'] >= 70000]

Empty DataFrame
Columns: [Company, Product, TypeName, Inches, Cpu, Ram, Gpu, OpSys, Weight, Price_euros, Cpu_Company, Memory_Amount, Memory_Type]
Index: []

Сколько дороже среднего

In [17]:
df[df['Price_euros'] >= df['Price_euros'].mean()]

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD
6,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.2GHz,16GB,Intel Iris Pro Graphics,Mac OS X,2.04,2139.97,Intel,256,FlashStorage
7,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,1158.70,Intel,256,FlashStorage
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256,Asus,Rog G752VT-GC073T,Gaming,17.3,Intel Core i7 6700HQ 2.6GHz,16GB,Nvidia GeForce GTX 970M,Windows 10,4.00,1900.00,Intel,128,HDD
1259,MSI,GE62 Apache,Gaming,15.6,Intel Core i7 6700HQ 2.6GHz,8GB,Nvidia GeForce GTX 960M,Windows 10,2.40,1229.00,Intel,128,HDD
1271,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.30,1499.00,Intel,512,SSD
1285,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.30,1499.00,Intel,512,SSD
1299,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.30,1499.00,Intel,512,SSD

## Задание 4.

Ответьте на несколько вопросов:

### 4.1 Найдите ноутбуки с самой маленькой диагональю в данных?
Выведите только следующие характеристики:
* Компания
* Типа ноутбука
* Диагональ
* Стоимость

Если таких ноутбуков несколько, то выводите их всех

In [18]:
df.head(1)

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD

In [19]:
df[df['Inches'] == df['Inches'].min()]

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
50,Lenovo,Yoga Book,2 in 1 Convertible,10.1,Intel Atom x5-Z8550 1.44GHz,4GB,Intel HD Graphics 400,Android,0.69,319.00,Intel,64,FlashStorage
1082,Lenovo,Yoga Book,2 in 1 Convertible,10.1,Intel Atom x5-Z8550 1.44GHz,4GB,Intel HD Graphics 400,Windows 10,0.69,646.27,Intel,64,FlashStorage
1114,Lenovo,Yoga Book,2 in 1 Convertible,10.1,Intel Atom x5-Z8550 1.44GHz,4GB,Intel HD Graphics 400,Android,0.69,549.00,Intel,64,FlashStorage
1126,Lenovo,Yoga Book,2 in 1 Convertible,10.1,Intel Atom x5-Z8550 1.44GHz,4GB,Intel HD Graphics 400,Windows 10,0.69,479.00,Intel,64,FlashStorage

In [20]:
a = df[df['Inches'] == df['Inches'].min()][['Company', 'TypeName', 'Inches', 'Price_euros']]
a

     Company            TypeName  Inches  Price_euros
50    Lenovo  2 in 1 Convertible    10.1       319.00
1082  Lenovo  2 in 1 Convertible    10.1       646.27
1114  Lenovo  2 in 1 Convertible    10.1       549.00
1126  Lenovo  2 in 1 Convertible    10.1       479.00

Другой вариант, но получаем все ряды отсортированные

In [21]:
df.sort_values('Inches')[['Company', 'TypeName', 'Inches', 'Price_euros']]

     Company            TypeName  Inches  Price_euros
1114  Lenovo  2 in 1 Convertible    10.1       549.00
1126  Lenovo  2 in 1 Convertible    10.1       479.00
1082  Lenovo  2 in 1 Convertible    10.1       646.27
50    Lenovo  2 in 1 Convertible    10.1       319.00
944   Lenovo  2 in 1 Convertible    11.3      1299.00
...      ...                 ...     ...          ...
1129      HP              Gaming    17.3      1129.00
578      MSI              Gaming    17.3      2729.00
257       HP            Notebook    17.3      1059.00
1136      HP         Workstation    17.3      3949.40
177      MSI              Gaming    18.4      2799.00

[1303 rows x 4 columns]

In [22]:
df.sort_values('Inches')[['Company', 'TypeName', 'Inches', 'Price_euros']].head(4)

     Company            TypeName  Inches  Price_euros
1114  Lenovo  2 in 1 Convertible    10.1       549.00
1126  Lenovo  2 in 1 Convertible    10.1       479.00
1082  Lenovo  2 in 1 Convertible    10.1       646.27
50    Lenovo  2 in 1 Convertible    10.1       319.00

### 4.2 Сколько стоит самый дорогой ноутбук у компании HP?

In [23]:
df[df['Company'] == 'HP']

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD
10,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,4GB,Intel HD Graphics 620,No OS,1.86,393.90,Intel,500,HDD
11,HP,250 G6,Notebook,15.6,Intel Core i3 6006U 2GHz,4GB,Intel HD Graphics 520,No OS,1.86,344.99,Intel,500,HDD
22,HP,255 G6,Notebook,15.6,AMD E-Series E2-9000e 1.5GHz,4GB,AMD Radeon R2,No OS,1.86,258.00,AMD,500,HDD
24,HP,15-BS101nv (i7-8550U/8GB/256GB/FHD/W10),Ultrabook,15.6,Intel Core i7 8550U 1.8GHz,8GB,Intel HD Graphics 620,Windows 10,1.91,659.00,Intel,256,SSD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282,HP,Stream 11-Y000na,Netbook,11.6,Intel Celeron Dual Core N3060 1.6GHz,2GB,Intel HD Graphics 400,Windows 10,1.17,209.00,Intel,32,FlashStorage
1287,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Intel Core i7 6500U 2.5GHz,6GB,AMD Radeon R5 M330,Windows 10,2.19,764.00,Intel,1024,HDD
1294,HP,Pavilion 15-AW003nv,Notebook,15.6,AMD A9-Series 9410 2.9GHz,6GB,AMD Radeon R7 M440,Windows 10,2.04,549.99,AMD,1024,Hybrid
1296,HP,Stream 11-Y000na,Netbook,11.6,Intel Celeron Dual Core N3060 1.6GHz,2GB,Intel HD Graphics 400,Windows 10,1.17,209.00,Intel,32,FlashStorage
1301,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Intel Core i7 6500U 2.5GHz,6GB,AMD Radeon R5 M330,Windows 10,2.19,764.00,Intel,1024,HDD

ascending =  False - по убыванию цены

In [24]:
df[df['Company'] == 'HP'].sort_values('Price_euros', ascending =  False)

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
749,HP,Zbook 17,Workstation,17.3,Intel Xeon E3-1535M v5 2.9GHz,16GB,Nvidia Quadro M2000M,Windows 7,3.00,4389.0,Intel,256,SSD
1136,HP,ZBook 17,Workstation,17.3,Intel Core i7 6700HQ 2.6GHz,8GB,Nvidia Quadro M3000M,Windows 7,3.00,3949.4,Intel,256,SSD
911,HP,Elitebook Folio,Ultrabook,12.5,Intel Core M 6Y75 1.2GHz,8GB,Intel HD Graphics 515,Windows 10,1.09,3100.0,Intel,240,SSD
1103,HP,ZBook 17,Workstation,17.3,Intel Core i7 6700HQ 2.6GHz,8GB,AMD FirePro W6150M,Windows 7,3.00,2899.0,Intel,1024,HDD
857,HP,EliteBook x360,2 in 1 Convertible,13.3,Intel Core i7 7600U 2.8GHz,8GB,Intel HD Graphics 620,Windows 10,1.28,2559.0,Intel,256,SSD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1168,HP,Stream 14-AX000nv,Notebook,14.0,Intel Celeron Dual Core N3060 1.6GHz,2GB,Intel HD Graphics 400,Windows 10,1.44,249.0,Intel,32,FlashStorage
67,HP,Stream 14-AX040wm,Notebook,14.0,Intel Celeron Dual Core N3060 1.6GHz,4GB,Intel HD Graphics 400,Windows 10,1.44,229.0,Intel,32,SSD
1268,HP,Stream 11-Y000na,Netbook,11.6,Intel Celeron Dual Core N3060 1.6GHz,2GB,Intel HD Graphics 400,Windows 10,1.17,209.0,Intel,32,FlashStorage
1282,HP,Stream 11-Y000na,Netbook,11.6,Intel Celeron Dual Core N3060 1.6GHz,2GB,Intel HD Graphics 400,Windows 10,1.17,209.0,Intel,32,FlashStorage
1296,HP,Stream 11-Y000na,Netbook,11.6,Intel Celeron Dual Core N3060 1.6GHz,2GB,Intel HD Graphics 400,Windows 10,1.17,209.0,Intel,32,FlashStorage

Только верхняя строчка

In [25]:
df[df['Company'] == 'HP'].sort_values('Price_euros', ascending =  False).head(1)

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
749,HP,Zbook 17,Workstation,17.3,Intel Xeon E3-1535M v5 2.9GHz,16GB,Nvidia Quadro M2000M,Windows 7,3.0,4389.0,Intel,256,SSD

In [26]:
df[df['Company'] == 'HP'].sort_values('Price_euros', ascending =  False).iloc[0]

Company                                     HP
Product                               Zbook 17
TypeName                           Workstation
Inches                                    17.3
Cpu              Intel Xeon E3-1535M v5 2.9GHz
Ram                                       16GB
Gpu                       Nvidia Quadro M2000M
OpSys                                Windows 7
Weight                                     3.0
Price_euros                             4389.0
Cpu_Company                              Intel
Memory_Amount                              256
Memory_Type                                SSD
Name: 749, dtype: object

In [27]:
df[df['Company'] == 'HP'].sort_values('Price_euros', ascending =  False).loc[749]

Company                                     HP
Product                               Zbook 17
TypeName                           Workstation
Inches                                    17.3
Cpu              Intel Xeon E3-1535M v5 2.9GHz
Ram                                       16GB
Gpu                       Nvidia Quadro M2000M
OpSys                                Windows 7
Weight                                     3.0
Price_euros                             4389.0
Cpu_Company                              Intel
Memory_Amount                              256
Memory_Type                                SSD
Name: 749, dtype: object

Количество

In [28]:
a.shape

(4, 4)

In [29]:
a.shape[0]

4

In [30]:
df.shape[0]

1303

### 4.3 Как много ноутбуков Ultrabook с 8GB RAM?

Найдите сколько таких ультрабуков с 8GB ОЗУ в процентном соотношении относительно всех ультрабуков

In [31]:
df.head(1)

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD

In [32]:
df[(df['TypeName'] == 'Ultrabook') & (df['Ram'] == '8GB')]

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,FlashStorage
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD
7,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,1158.70,Intel,256,FlashStorage
9,Acer,Swift 3,Ultrabook,14.0,Intel Core i5 8250U 1.6GHz,8GB,Intel UHD Graphics 620,Windows 10,1.60,770.00,Intel,256,SSD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236,HP,EliteBook 840,Ultrabook,14.0,Intel Core i7 6500U 2.5GHz,8GB,Intel HD Graphics 520,Windows 7,1.54,2198.19,Intel,256,SSD
1241,Asus,ZenBook UX310UA-WB71,Ultrabook,13.3,Intel Core i7 6500U 2.5GHz,8GB,Intel HD Graphics 520,Windows 10,1.45,1280.00,Intel,256,SSD
1261,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Intel Core M 6Y30 0.9GHz,8GB,Intel HD Graphics 515,Windows 10,1.20,729.00,Intel,512,SSD
1275,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Intel Core M 6Y30 0.9GHz,8GB,Intel HD Graphics 515,Windows 10,1.20,729.00,Intel,512,SSD
1289,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Intel Core M 6Y30 0.9GHz,8GB,Intel HD Graphics 515,Windows 10,1.20,729.00,Intel,512,SSD

In [33]:
number_8_RAM = df[(df['TypeName'] == 'Ultrabook') & (df['Ram'] == '8GB')].shape[0]
number_8_RAM

140

In [34]:
number_Ultra = df[df['TypeName'] == 'Ultrabook'].shape[0]
number_Ultra

196

In [35]:
number_8_RAM / number_Ultra * 100

71.42857142857143

Через normalize=True соотношение

In [36]:
df[df['TypeName'] == 'Ultrabook']['Ram'].value_counts(normalize=True)

8GB     0.714286
16GB    0.183673
4GB     0.071429
12GB    0.015306
24GB    0.005102
32GB    0.005102
6GB     0.005102
Name: Ram, dtype: float64

In [37]:
df[df['TypeName'] == 'Ultrabook']

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD
1,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,FlashStorage
3,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD
4,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD
6,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.2GHz,16GB,Intel Iris Pro Graphics,Mac OS X,2.04,2139.97,Intel,256,FlashStorage
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236,HP,EliteBook 840,Ultrabook,14.0,Intel Core i7 6500U 2.5GHz,8GB,Intel HD Graphics 520,Windows 7,1.54,2198.19,Intel,256,SSD
1241,Asus,ZenBook UX310UA-WB71,Ultrabook,13.3,Intel Core i7 6500U 2.5GHz,8GB,Intel HD Graphics 520,Windows 10,1.45,1280.00,Intel,256,SSD
1261,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Intel Core M 6Y30 0.9GHz,8GB,Intel HD Graphics 515,Windows 10,1.20,729.00,Intel,512,SSD
1275,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Intel Core M 6Y30 0.9GHz,8GB,Intel HD Graphics 515,Windows 10,1.20,729.00,Intel,512,SSD
1289,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Intel Core M 6Y30 0.9GHz,8GB,Intel HD Graphics 515,Windows 10,1.20,729.00,Intel,512,SSD

In [38]:
df[df['TypeName'] == 'Ultrabook']['Ram']

0        8GB
1        8GB
3       16GB
4        8GB
6       16GB
        ...
1236     8GB
1241     8GB
1261     8GB
1275     8GB
1289     8GB
Name: Ram, Length: 196, dtype: object

In [39]:
df[df['TypeName'] == 'Ultrabook']['Ram'].value_counts()

8GB     140
16GB     36
4GB      14
12GB      3
24GB      1
32GB      1
6GB       1
Name: Ram, dtype: int64

## Задание 5.

### 5.1 Выберите ноутбук клиенту
Клиент хочет подобрать ноутбук с 8GB или 16GB ОЗУ на Windows 10 в стоимости до 500 евро, сколько у него вариантов?

In [40]:
df.head(1)

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD

In [41]:
df.TypeName.value_counts()

Notebook              727
Gaming                205
Ultrabook             196
2 in 1 Convertible    121
Workstation            29
Netbook                25
Name: TypeName, dtype: int64

In [42]:
df.TypeName.unique()

array(['Ultrabook', 'Notebook', 'Netbook', 'Gaming', '2 in 1 Convertible',
       'Workstation'], dtype=object)

In [43]:
result_1 = df[
    (df['TypeName'] == 'Notebook') & 
    ((df['Ram'] == '8GB') | (df['Ram'] == '16GB')) &
    (df['OpSys'] <= 'Windows 10') &
    (df['Price_euros'] <= 25000)
] 
result_1

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
2,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD
16,Dell,Inspiron 3567,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,AMD Radeon R5 M430,Windows 10,2.20,745.00,Intel,256,SSD
18,Lenovo,IdeaPad 320-15IKB,Notebook,15.6,Intel Core i3 7100U 2.4GHz,8GB,Nvidia GeForce 940MX,No OS,2.20,499.00,Intel,1024,HDD
27,Dell,Inspiron 5570,Notebook,15.6,Intel Core i5 8250U 1.6GHz,8GB,AMD Radeon 530,Windows 10,2.20,800.00,Intel,256,SSD
29,HP,ProBook 470,Notebook,17.3,Intel Core i5 8250U 1.6GHz,8GB,Nvidia GeForce 930MX,Windows 10,2.50,896.00,Intel,1024,HDD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,Dell,Inspiron 3567,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,AMD Radeon R5 M430,Linux,2.30,805.99,Intel,1024,HDD
1279,Lenovo,IdeaPad Y700-15ISK,Notebook,15.6,Intel Core i7 6700HQ 2.6GHz,8GB,Nvidia GeForce GTX 960M,Windows 10,2.60,899.00,Intel,1024,HDD
1281,Dell,Inspiron 3567,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,AMD Radeon R5 M430,Linux,2.30,805.99,Intel,1024,HDD
1293,Lenovo,IdeaPad Y700-15ISK,Notebook,15.6,Intel Core i7 6700HQ 2.6GHz,8GB,Nvidia GeForce GTX 960M,Windows 10,2.60,899.00,Intel,1024,HDD
1295,Dell,Inspiron 3567,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,AMD Radeon R5 M430,Linux,2.30,805.99,Intel,1024,HDD

In [44]:
result_1.shape[0]

331

### 5.2 Выберите ноутбук клиенту
Клиент хочет подобрать ноутбук от MSI, с видеокартой Nvidia GeForce GTX 1050 Ti и главное не с диагональю 15.6. В какой ценовой категории вышли подобные ноутбуки?

In [45]:
df[(df['Company'] == 'MSI') & (df['Gpu'] == 'Nvidia GeForce GTX 1050 Ti') & ~(df['Gpu'] == 'Nvidia GeForce GTX 1050 Ti')]

Empty DataFrame
Columns: [Company, Product, TypeName, Inches, Cpu, Ram, Gpu, OpSys, Weight, Price_euros, Cpu_Company, Memory_Amount, Memory_Type]
Index: []

In [46]:
df[
    (df['Company'] == 'MSI') & 
    (df['Gpu'] == 'Nvidia GeForce GTX 1050 Ti') & 
    ~(df['Inches'] == 15.6)
]

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
330,MSI,GL72M 7REX,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1199.00,Intel,256,HDD
393,MSI,Leopard GP72M,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1349.00,Intel,256,SSD
724,MSI,GL72M 7REX,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1348.48,Intel,128,HDD
917,MSI,GE72VR 6RF,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1599.00,Intel,256,HDD
1156,MSI,GP72M 7REX,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1492.80,Intel,256,HDD

In [47]:
number_nit_inches = df[
    (df['Company'] == 'MSI') & 
    (df['Gpu'] == 'Nvidia GeForce GTX 1050 Ti') & 
    (df['Inches'] != 15.6)
] 
number_nit_inches

,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
330,MSI,GL72M 7REX,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1199.00,Intel,256,HDD
393,MSI,Leopard GP72M,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1349.00,Intel,256,SSD
724,MSI,GL72M 7REX,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1348.48,Intel,128,HDD
917,MSI,GE72VR 6RF,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1599.00,Intel,256,HDD
1156,MSI,GP72M 7REX,Gaming,17.3,Intel Core i7 7700HQ 2.8GHz,16GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.7,1492.80,Intel,256,HDD

In [48]:
number_nit_inches['Price_euros'].min(), number_nit_inches['Price_euros'].max()

(1199.0, 1599.0)

In [49]:
result = number_nit_inches['Price_euros'].min(), number_nit_inches['Price_euros'].max()
result[0]

1199.0

### 5.3 Что дешевле?
В среднем дешевле ноутбуки с CPU Intel Core i7 7700HQ 2.8GHz или с Intel Core i7 7600U 2.8GHz?

In [50]:
number_1 = df[df['Cpu'] == 'Intel Core i7 7700HQ 2.8GHz']['Price_euros'].mean()
number_1

1760.4084246575342

In [51]:
number_2 = df[df['Cpu'] == 'Intel Core i7 7600U 2.8GHz']['Price_euros'].mean()
number_2

1915.710769230769

In [52]:
number_1, number_2

(1760.4084246575342, 1915.710769230769)

In [53]:
number_1 > number_2

False

## Задание 6.

Найдите самый легкий ноутбук
Но обратите внимание на тип и представление данных в признаке Weight, если что, замените в строке 'kg' на пустую строку через метод .str.replace()

In [54]:
df = pd.read_csv('./laptop_data.csv', encoding='latin-1')

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        1303 non-null   int64
 1   Company           1303 non-null   object
 2   TypeName          1303 non-null   object
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object
 5   Cpu               1303 non-null   object
 6   Ram               1303 non-null   object
 7   Memory            1303 non-null   object
 8   Gpu               1303 non-null   object
 9   OpSys             1303 non-null   object
 10  Weight            1303 non-null   object
 11  Price             1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB

In [56]:
df['Weight']

0       1.37kg
1       1.34kg
2       1.86kg
3       1.83kg
4       1.37kg
         ...
1298     1.8kg
1299     1.3kg
1300     1.5kg
1301    2.19kg
1302     2.2kg
Name: Weight, Length: 1303, dtype: object

In [57]:
df['Weight'].value_counts()

2.2kg     121
2.1kg      58
2.4kg      44
2.3kg      41
2.5kg      38
         ...
3.25kg      1
4.7kg       1
1.55kg      1
1.18kg      1
4.0kg       1
Name: Weight, Length: 179, dtype: int64

Перезаписываем этот столбец
.str.replace('kg', '') - меняем что-то на что-то

In [58]:
df['Weight'] = df['Weight'].str.replace('kg', '')
df

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86,30636.0000
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83,135195.3360
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37,96095.8080
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,Lenovo,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8,33992.6400
1299,1299,Lenovo,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3,79866.7200
1300,1300,Lenovo,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5,12201.1200
1301,1301,HP,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19,40705.9200
1302,1302,Asus,Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2,19660.3200

In [59]:
df.Weight

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298     1.8
1299     1.3
1300     1.5
1301    2.19
1302     2.2
Name: Weight, Length: 1303, dtype: object

Поменять тип данных

In [60]:
df['Weight'] = df['Weight'].astype(float)

In [61]:
df.Weight

0       1.37
1       1.34
2       1.86
3       1.83
4       1.37
        ...
1298    1.80
1299    1.30
1300    1.50
1301    2.19
1302    2.20
Name: Weight, Length: 1303, dtype: float64